//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace beadando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int player_id { get; set; }
        public string name { get; set; }
        public int age { get; set; }
        public string password { get; set; }
        public int score { get; set; }
    }
}
